cmake_minimum_required(VERSION 3.2)

set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_VERSION 1)
set(CMAKE_SYSTEM_PROCESSOR "aarch64")
set(CMAKE_CROSSCOMPILING 1)

set(DEVKITPRO $ENV{DEVKITPRO})

set(TOOL_PREFIX ${DEVKITPRO}/devkitA64/bin/aarch64-none-elf-)

set(CMAKE_ASM_COMPILER ${TOOL_PREFIX}gcc    CACHE PATH "")
set(CMAKE_C_COMPILER   ${TOOL_PREFIX}gcc    CACHE PATH "")
set(CMAKE_CXX_COMPILER ${TOOL_PREFIX}g++    CACHE PATH "")
set(CMAKE_LINKER       ${TOOL_PREFIX}g++    CACHE PATH "")
set(CMAKE_AR           ${TOOL_PREFIX}ar     CACHE PATH "")
set(CMAKE_STRIP        ${TOOL_PREFIX}strip  CACHE PATH "")

SET(BUILD_SHARED_LIBS OFF CACHE INTERNAL "Shared libs not available" )
set (DKA_SWITCH_C_FLAGS "-D__SWITCH__ -DSWITCH -march=armv8-a+crc+crypto -mtune=cortex-a57 -mtp=soft -ftls-model=local-exec -ffunction-sections -fdata-sections")
set(CMAKE_C_FLAGS   "${DKA_SWITCH_C_FLAGS}" CACHE STRING "")
set(CMAKE_CXX_FLAGS "${DKA_SWITCH_C_FLAGS}" CACHE STRING "")
set(CMAKE_ASM_FLAGS "${DKA_SWITCH_C_FLAGS}" CACHE STRING "")

set(NSWITCH TRUE)

set(CMAKE_POSITION_INDEPENDENT_CODE ON)

set(NX_ROOT ${DEVKITPRO}/libnx)

set(NX_STANDARD_INCLUDE_DIRECTORIES "${NX_ROOT}/include")
set(CMAKE_C_STANDARD_INCLUDE_DIRECTORIES "${NX_STANDARD_INCLUDE_DIRECTORIES}" CACHE STRING "")
set(CMAKE_CXX_STANDARD_INCLUDE_DIRECTORIES "${NX_STANDARD_INCLUDE_DIRECTORIES}" CACHE STRING "")
set(CMAKE_ASM_STANDARD_INCLUDE_DIRECTORIES "${NX_STANDARD_INCLUDE_DIRECTORIES}" CACHE STRING "")

